spring:
  application:
    name: graphql-example
  datasource:
    username: s
    url: jdbc:postgresql://localhost:5432/mydatabase
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
graphql:
  graphiql:
    mapping: /graphiql
    enabled: 'true'
    static:
      basePath: /graphiql
  servlet:
    mapping: /graphql

